displayName=Ultimate Pker
author=28 of 808
description=Restrictions on banking, trading and the GE
tags=trade,ge,grand exchange,pking,bank,restriction,ironman
plugins=com.ultimatepkmanmode.UltimatePkerPlugin